#!/bin/bash

STACK_DIR="/opt/media-stack"

case "$1" in

update)

cd $STACK_DIR
docker compose pull
docker compose up -d
;;

backup)

tar -czf media-stack-backup-$(date +%Y%m%d).tar.gz $STACK_DIR/config
;;

status)

docker ps
;;

logs)

docker compose -f $STACK_DIR/docker-compose.yml logs -f
;;

*)

echo "Media Stack CLI"
echo ""
echo "media-stack update"
echo "media-stack backup"
echo "media-stack status"
echo "media-stack logs"

;;

esac
