version: "3.9"

########################################
# Docker Networks
########################################

networks:
  media-network:
    driver: bridge

########################################
# Base Services Section
########################################

services:
